version: '2'
services:
  app:
    container_name: app
    build: .
    volumes:
      - .:/var/www
    depends_on:
      - webserver
      - db

  webserver:
    container_name: webserver
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./provision/vhost.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    container_name: php
    image: php:7.0-fpm
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"

  db:
    container_name: db
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "warehouse"
      MYSQL_ROOT_USER: "warehouse"
      MYSQL_ROOT_PASSWORD: "daSkiI357&34dfd12"
